### ISSUE TITLE
找不到android端图片资源的位置

### ISSUE THREAD

**Issue by TheLiyo** [jpush/jverify-flutter-plugin#100]
如题...
不好意思我对安卓了解的不多。
我想修改一下图片资源，但是找来找去没看到图片在哪...

**Comment by skill20** [comment]
在android 目录里

**Comment by hyhSuper** [comment]
图片资源替换 android项目将图片存放至drawable文件夹下，可使用图片选择器的文件名,例如：btn_login.xml,入参为"btn_login"。
 ios项目存放在 Assets.xcassets。
