### ISSUE TITLE
隐私协议展示web页面导航栏背景色白色，怎么设置返回按钮颜色？

### ISSUE THREAD

**Issue by phoenixsky** [jpush/jverify-flutter-plugin#130]
怎么去返回按钮的颜色？
如果设置新的图片，无法做到在导航栏竖直居中

**Comment by skill20** [comment]
暂时没有这个设置接口。

**Comment by phoenixsky** [comment]
![image](https://user-images.githubusercontent.com/6359214/123983427-700cc780-d9f6-11eb-99cf-9a98952ee9a9.png)

使用uiConfig.privacyNavReturnBtnImage设置图片后，按钮不居中
