### ISSUE TITLE
说明文档写的太烂采坑，写下过程，以备其他人采坑

### ISSUE THREAD

**Issue by beelzebub2006** [jpush/jverify-flutter-plugin#132]
按照文档git下来后直接改参数后死活就是初始化失败。得先按照https://docs.jiguang.cn/jverification/client/android_guide/的android方式配好，把libs和jniLibs文件夹都拷贝过来。AndroidManifest.xml文件把权限都配上。才可以初始化成功。坑呀！！

"developer-default"还写成了"devloper-default"了！

**Comment by skill20** [comment]
感谢反馈，我们后续改进。

**Comment by onlyYU** [comment]
+1
