### ISSUE TITLE
加入该组件后报错

### ISSUE THREAD

**Issue by qq125183592** [jpush/jverify-flutter-plugin#2]
请求作者帮助，与fluwx组件有相关冲突
```
 Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: warning: ignoring file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_login_sdk_noui_core.framework/account_login_sdk_noui_core, missing required architecture x86_64 in file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_login_sdk_noui_core.framework/account_login_sdk_noui_core (2 slices)
    ld: warning: ignoring file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_verify_sdk_core.framework/account_verify_sdk_core, missing required architecture x86_64 in file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_verify_sdk_core.framework/account_verify_sdk_core (2 slices)
    duplicate symbol __registrar in:
        /Users/yujie/AndroidStudioProjects/flutter_app/build/ios/Debug-iphonesimulator/fluwx/libfluwx.a(FluwxShareHandler.o)
        /Users/yujie/AndroidStudioProjects/flutter_app/build/ios/Debug-iphonesimulator/jverify/libjverify.a(JverifyPlugin.o)
    ld: 1 duplicate symbol for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

我们工程使用的组件有
```
  fluwx: ^1.0.4 #微信登录、分享、支付等能力
  jverify: 0.0.1
```

**Comment by skill20** [comment]
> 请求作者帮助，与fluwx组件有相关冲突
> 
> ```
>  Xcode's output:
> ↳
>     === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
>     ld: warning: ignoring file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_login_sdk_noui_core.framework/account_login_sdk_noui_core, missing required architecture x86_64 in file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_login_sdk_noui_core.framework/account_login_sdk_noui_core (2 slices)
>     ld: warning: ignoring file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_verify_sdk_core.framework/account_verify_sdk_core, missing required architecture x86_64 in file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/JVerification/account_verify_sdk_core.framework/account_verify_sdk_core (2 slices)
>     duplicate symbol __registrar in:
>         /Users/yujie/AndroidStudioProjects/flutter_app/build/ios/Debug-iphonesimulator/fluwx/libfluwx.a(FluwxShareHandler.o)
>         /Users/yujie/AndroidStudioProjects/flutter_app/build/ios/Debug-iphonesimulator/jverify/libjverify.a(JverifyPlugin.o)
>     ld: 1 duplicate symbol for architecture x86_64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> 我们工程使用的组件有
> 
> ```
>   fluwx: ^1.0.4 #微信登录、分享、支付等能力
>   jverify: 0.0.1
> ```

升级到最新版本

**Comment by skill20** [comment]
升级到最新版本

**Comment by qq125183592** [comment]
谢谢，目前没用到这部分了，到时我也再试试
