### ISSUE TITLE
appkey不是一键登录用户

### ISSUE THREAD

**Issue by 0123cf** [jpush/jverify-flutter-plugin#28]
为什么QAQ
```
，code=4033,message = appkey is not support login,operator
 = null
```

appkey取的位置
![image](https://user-images.githubusercontent.com/22963895/66751342-6e693c00-eec1-11e9-8396-b2522bae952f.png)

**Comment by 0123cf** [comment]
![image](https://user-images.githubusercontent.com/22963895/66808590-264c2700-ef5e-11e9-8f0b-d4088002fd00.png)
需要在这里提交审核

**Comment by mencomao** [comment]
已经提交审核，并且审核通过， 还是提示4033
