### ISSUE TITLE
flutter build apk 安卓无法一键登录

### ISSUE THREAD

**Issue by Tecode** [jpush/jverify-flutter-plugin#45]
谷歌`flutter build apk`命令运行时会自动使用`R8`压缩，解决方法是加上参数`--no-shrink`,目前暂时的解决方法。
希望解决一下混淆这个问题
```
flutter build apk --release --target-platform=android-arm64 --no-shrink
```

**Comment by skill20** [comment]
官网 Flutter WIKI 里面说，Dart 的混淆还没有完全测试

**Comment by jcleng** [comment]
> 谷歌`flutter build apk`命令运行时会自动使用`R8`压缩，解决方法是加上参数`--no-shrink`,目前暂时的解决方法。
> 希望解决一下混淆这个问题
> 
> ```
> flutter build apk --release --target-platform=android-arm64 --no-shrink
> ```

这边小米se8se miui 10.2 会出现这个问题`preLogin failed`,加上`--no-shrink`就可以了,其他安卓机没有重现,估计部分机型需要加上 

```log
I/flutter ( 4155): | JVER | Flutter | isInitSuccess
I/flutter ( 4155): | JVER | Flutter | checkVerifyEnable
I/flutter ( 4155): | JVER | Flutter | preLogin{timeOut: 10000}
I/flutter ( 4155): {code: 7001, message: preLogin failed}
I/flutter ( 4155): | JVER | Flutter | isInitSuccess
I/flutter ( 4155): | JVER | Flutter | checkVerifyEnable
```

**Comment by wuuJiawei** [comment]
小米9 MIUI12.0.2 Android10
