### ISSUE TITLE
ITMS-90809

### ISSUE THREAD

**Issue by hanleiZoro** [jpush/jverify-flutter-plugin#51]
我在处理苹果废弃UIWebView提示时，我查找项目依赖文件是否包含 UIWebView 接口。
<img width="575" alt="截屏2020-04-24上午12 42 06" src="https://user-images.githubusercontent.com/38712031/80125450-3f482b80-85c4-11ea-93a5-be516f50028c.png">
能否麻烦帮吗看一下

**Comment by popeyelau** [comment]
这个问题解决了吗？
