### ISSUE TITLE
google play 上架问题

### ISSUE THREAD

**Issue by leielyq** [jpush/jverify-flutter-plugin#63]
APK REQUIRES PROMINENT DISCLOSURE​
We’ve identified that your app is using Jiguang SDK or library, which facilitates the transmission of collection of installed packages information without meeting the prominent disclosure guidelines. If necessary, you can consult your SDK provider(s) for further information.

**Comment by leielyq** [comment]
没有人吗

**Comment by skill20** [comment]
认证sdk暂时不支持google play上架.

**Comment by leielyq** [comment]
@skill20  加油哦
