### ISSUE TITLE
No implementation found for method setup on channel jverify

### ISSUE THREAD

**Issue by long51xy** [jpush/jverify-flutter-plugin#76]
I/flutter ( 7430): | JVER | Flutter | setDebugMode
I/flutter ( 7430): | JVER | Flutter | setup
E/flutter ( 7430): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method setDebugMode on channel jverify)
E/flutter ( 7430): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 7430): <asynchronous suspension>
E/flutter ( 7430): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7430): #2      Jverify.setDebugMode (package:jverify/jverify.dart:182:14)
E/flutter ( 7430): #3      _MyAppState.initPlatformState (package:jverify_example/main.dart:494:13)
E/flutter ( 7430): #4      _MyAppState.initState (package:jverify_example/main.dart:48:5)
E/flutter ( 7430): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4644:58)
E/flutter ( 7430): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 7430): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 7430): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 7430): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 7430): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 7430): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 7430): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 7430): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter ( 7430): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 7430): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 7430): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 7430): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 7430): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter ( 7430): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #45     Element.updateCh
E/flutter ( 7430): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method setup on channel jverify)
E/flutter ( 7430): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 7430): <asynchronous suspension>
E/flutter ( 7430): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7430): #2      Jverify.setup (package:jverify/jverify.dart:171:14)
E/flutter ( 7430): #3      _MyAppState.initPlatformState (package:jverify_example/main.dart:495:13)
E/flutter ( 7430): #4      _MyAppState.initState (package:jverify_example/main.dart:48:5)
E/flutter ( 7430): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4644:58)
E/flutter ( 7430): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 7430): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 7430): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 7430): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 7430): #25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 7430): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 7430): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 7430): #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter ( 7430): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5834:14)
E/flutter ( 7430): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
E/flutter ( 7430): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
E/flutter ( 7430): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
E/flutter ( 7430): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
E/flutter ( 7430): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter ( 7430): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
E/flutter ( 7430): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
E/flutter ( 7430): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
E/flutter ( 7430): #45     Element.updateChild (package:f
D/EGL_emulation( 7430): eglMakeCurrent: 0xec065f50: ver 2 0 (tinfo 0xec3bc4b0)
I/flutter ( 7430): | JVER | Flutter | checkVerifyEnable
E/flutter ( 7430): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method checkVerifyEnable on channel jverify)
E/flutter ( 7430): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 7430): <asynchronous suspension>
E/flutter ( 7430): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7430): #2      Jverify.checkVerifyEnable (package:jverify/jverify.dart:238:27)
E/flutter ( 7430): #3      _MyAppState.preLogin (package:jverify_example/main.dart:253:13)
E/flutter ( 7430): #4      _MyAppState._buildContent.<anonymous closure> (package:jverify_example/main.dart:122:19)
E/flutter ( 7430): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:772:19)
E/flutter ( 7430): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:855:36)
E/flutter ( 7430): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7430): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
E/flutter ( 7430): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 7430): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 7430): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 7430): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 7430): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 7430): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 7430): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 7430): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 7430): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 7430): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7430): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7430): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7430): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7430): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 7430): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7430): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 7430): #25     _invoke1 (dart:ui/hooks.dart:291:10)
E/flutter ( 7430): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:200:5)
E/flutter ( 7430):
Application finished.

尝试各种方法还是不行，拉你们的示例代码也是报这个

**Comment by ningyibo** [comment]
这个好像是flutter版本升级到17之后才出现的，我之前的flutter版本比较旧就ok，前两天更新了一下版本也就出现这个问题了，只能手动去regist了

**Comment by long51xy** [comment]
> 这个好像是flutter版本升级到17之后才出现的，我之前的flutter版本比较旧就ok，前两天更新了一下版本也就出现这个问题了，只能手动去regist了

怎么手动注册，注册的那个类都是自动生成的

**Comment by ningyibo** [comment]
> > 这个好像是flutter版本升级到17之后才出现的，我之前的flutter版本比较旧就ok，前两天更新了一下版本也就出现这个问题了，只能手动去regist了
> 
> 怎么手动注册，注册的那个类都是自动生成的

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
        registerPlugin();
     }
    private void registerPlugin() {
        if (!hasPlugin("com.jiguang.jverify.JverifyPlugin")) {
            JverifyPlugin.registerWith(registrarFor("com.jiguang.jverify.JverifyPlugin"));
        }
    }
 }


这样就可以了

**Comment by popeyelau** [comment]
更新到 `0.6.12`后会出现这个问题，已回退到 `0.6.9`
