### ISSUE TITLE
The number of method references in a .dex file cannot exceed 64K.

### ISSUE THREAD

**Issue by 370966584** [jpush/jverify-flutter-plugin#79]
![image](https://user-images.githubusercontent.com/26058251/86749504-e4c15600-c06f-11ea-9b13-acc747da5659.png)
![image](https://user-images.githubusercontent.com/26058251/86749557-edb22780-c06f-11ea-9096-41fa0609de90.png)

flutter 1.12.13 引入报错

**Comment by skill20** [comment]
开启 mutil dex
