### ISSUE TITLE
iOS 调用preLogin闪退

### ISSUE THREAD

**Issue by long51xy** [jpush/jverify-flutter-plugin#84]
AMapLocationManagerDelegate::amapLocationManager_didUpdateLocation_reGeocode
AMapLocationManagerDelegate::amapLocationManager_didUpdateLocation_reGeocode
AMapLocationManagerDelegate::amapLocationManager_didUpdateLocation_reGeocode
| JVER | iOS | Action - handleMethodCall: preLogin
| JVER | iOS | Action - preLogin::{
    timeOut = 10000;
}
 | JIGUANG | D - [JIGUANGService] preLogin:completion:
[Bugly]  Trapped uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1f05057f0'
(
	0   CoreFoundation                      0x00000001c04329a4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001bf60b9f8 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001c034f1c8 <redacted> + 0
	3   CoreFoundation                      0x00000001c04381d4 <redacted> + 1408
	4   CoreFoundation                      0x00000001c0439e6c _CF_forwarding_prep_0 + 92
	5   Runner                              0x000000010251b8c8 -[JVOperatorAdapter LoginFeatureEnable] + 168
	6   Runner                              0x0000000102507738 -[JVOperatorController validatePreloginCache] + 140
	7   Runner                              0x0000000102503180 -[JVClientController validePreloginCache] + 96
	8   Runner                              0x0000000102513198 +[JVERIFICATIONService preLogin:completion:] + 1476
	9   Runner                              0x0000000102d76644 -[JverifyPlugin preLogin:result:] + 428
	10  Runner                              0x0000000102d7430c -[JverifyPlugin handleMethodCall:result:] + 824
	11  Flutter                             0x0000000103883270 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 116
	12  Flutter                             0x000000010381a07c _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 504
	13  Flutter                             0x000000010387388c _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_32NS_9allocatorIS8_EEFvvEEclEv + 80
	14  Flutter                             0x000000010382a928 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 1616
	15  Flutter                             0x000000010382cc8c _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
	16  CoreFoundation                      0x00000001c03c4d60 <redacted> + 28
	17  CoreFoundation                      0x00000001c03c4a90 <redacted> + 864
	18  CoreFoundation                      0x00000001c03c42c4 <redacted> + 248
	19  CoreFoundation                      0x00000001c03bf214 <redacted> + 1844
	20  CoreFoundation                      0x00000001c03be7c0 CFRunLoopRunSpecific + 436
	21  GraphicsServices                    0x00000001c25bf79c GSEventRunModal + 104
	22  UIKitCore                           0x00000001ecd3dc38 UIApplicationMain + 212
	23  Runner                              0x000000010242e778 main + 80
	24  libdyld.dylib                       0x00000001bfe828e0 <redacted> + 4
)
[Bugly] Fatal signal(6) raised.
[Bugly] Forward signal(6) to the previous handler: 0x0
Lost connection to device.
Exited (sigterm)

sdk  jverify: 0.6.14

**Comment by skill20** [comment]
您检查一下 ios key 的配置。

**Comment by long51xy** [comment]
> 您检查一下 ios key 的配置。

谢谢解决了，我重新清除一边就可以了
