### ISSUE TITLE
SDK 初始化失败

### ISSUE THREAD

**Issue by yuchao86** [jpush/jverify-flutter-plugin#85]
Performing hot reload...
Syncing files to device sdk gphone x86 arm...
Reloaded 0 of 501 libraries in 491ms.
I/flutter (10341): | JVER | Flutter | isInitSuccess
D/| JVER | Android | -(10341): onMethodCall:isInitSuccess
D/| JVER | Android | -(10341): processMethod:isInitSuccess
D/| JVER | Android | -(10341): Action - isInitSuccess:
D/| JVER | Android | -(10341): SDK 初始化失败:

**Comment by skill20** [comment]
接入配置是否按照文档接入的？
