### ISSUE TITLE
getSMSCode的验证码验证api哪里可以找到？

### ISSUE THREAD

**Issue by wengxianxun** [jpush/jverify-flutter-plugin#90]
getSMSCode
获取短信验证码，使用此功能需要在Portal控制台中极光短信模块添加短信签名和验证码短信模版，或者使用默认的签名或模版

说明： 通过此接口获得到短信验证码后，需要调用极光验证码验证API来进行验证。

**Comment by wengxianxun** [comment]
https://docs.jiguang.cn/jsms/server/rest_api_jsms/#api_3   这里短信验证码验证需要提供msg_id， 但是getSMSCode返回的根本就没有msg_id这个字段

**Comment by hyhSuper** [comment]
成功时返回的uuid 就是对应的msg_id.
