### ISSUE TITLE
要实现一键登录，一定要跳转到官方的JVAuthPage界面么？

### ISSUE THREAD

**Issue by DennisJu007** [jpush/jverify-flutter-plugin#92]
我调用的是jverify.loginAuth和jverify.loginAuthSyncApi方法都会跳转到官方定义的界面，我们能否自定义这个界面而且这样搞IOS会不会要求支持AppleID登录，不然审核通不过。可不可以不跳转直接自定义界面点击按钮获取登录的token呢

**Comment by skill20** [comment]
可以参考一下无UI版本，可以联系客服

**Comment by DennisJu007** [comment]
客服怎么联系呢，他能直接提供demo么

**Comment by skill20** [comment]
需要经过运营审核

**Comment by DennisJu007** [comment]
谢谢，已通过官网客服反馈，相关技术支持还没介入
